name: Stealth-sync engine

on:
  schedule:
    - cron: '14 3,7,10,12,14,16,18,21 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set Git Identity
      run: |
        git config --global user.name "SaurabhCodesAI"
        git config --global user.email "saurabhpareek228@gmail.com"

    - name: Sync Activity Logs
      run: |
        export TZ=$(shuf -n 1 -e Asia/Kolkata Europe/Berlin America/New_York)
        NUM=$((RANDOM % 4 + 2))  # 2–5 commits per run

        for i in $(seq 1 $NUM); do
          DIR=$(shuf -n 1 -e logs data notes scratch)
          mkdir -p "$DIR"
          FILE="$DIR/log_$(date +%s%N).md"
          echo "Log $i at $(date)" > "$FILE"
          echo "Generated output: $(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 20)" >> "$FILE"
          git add "$FILE"
          git commit -m "Log update: $(head /dev/urandom | tr -dc A-Za-z | head -c 8)"
          sleep $((RANDOM % 90 + 30))
        done

        git pull --rebase
        git push
